#!/bin/bash

# initialize directory, current directory should be src
current_dir=`pwd`
src_dir=$current_dir # current is the src directory
bin_dir=$current_dir/../bin
lib_dir=$current_dir/../lib

# make the library and binary directories
mkdir -p $bin_dir
mkdir -p $lib_dir

# link some configuration files to bin directory
ln -s $src_dir/dictionary.xml $bin_dir/dictionary.xml
ln -s $src_dir/input_file.msg $bin_dir/input_file.msg
ln -s $src_dir/config.conf $bin_dir/config.conf
ln -s $src_dir/task.t $bin_dir/task.t
ln -s $src_dir/trace_flag $bin_dir/trace_flag

# currently only consider the ubuntu 32bit distribution
ln -s $src_dir/ubuntu/32bit/libxerces-c.so $bin_dir/libxerces-c.so.28
ln -s $src_dir/ubuntu/32bit/libxerces-c.so $lib_dir/libxerces-c.so

# generate the enironment variables scripts to bin
echo "#!/bin/bash" > $bin_dir/set
echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:." >> $bin_dir/set
chmod 755 $bin_dir/set
